---

- name: Clone the Alert Notification repository
  become_user: "{{ ops_user }}"
  git:
    repo: git@github.ibm.com:OMaaS/alert-notification.git
    dest: /home/{{ ops_user }}/scm/alert-notification
    force: yes
    accept_hostkey: yes
 
- name: Clone the Replication Tool
  become_user: "{{ ops_user }}"
  git:
    repo: git@github.ibm.com:OMaaS/replication-tools.git
    dest: /home/{{ ops_user }}/replication-tools
    force: yes
    accept_hostkey: yes

- name: Install node.js packages for replication-tools
  npm:
    name: "{{item}}"
    path: /home/{{ ops_user }}/replication-tools
  with_items:
       - command-line-args
       - command-line-usage
       - bunyan
       - ramda
       - nano

- name: Copy dutchTaxOffice_del_archives file
  copy:
    src: dutchTaxOffice_del_archives.sh
    dest: "/home/{{ ops_user }}/scm/alert-notification/tools/dbreducer/"
    mode: "755"
    owner: "{{ ops_user }}"
    group: "{{ ops_user }}"

- name: Copy substats_report.sh file
  copy:
    src: substats_report.sh
    dest: "/home/{{ ops_user }}/scripts/"
    mode: "755"
    owner: "{{ ops_user }}"
    group: "{{ ops_user }}"
    
- name: Copy substats.py file
  copy:
    src: substats.py
    dest: "/home/{{ ops_user }}/scripts/"
    mode: "755"
    owner: "{{ ops_user }}"
    group: "{{ ops_user }}"
    
- name: Install substats_report cron job
  become_user: "{{ ops_user }}"
  cron:
    name: substats report
    minute: 0,15,30,45
    job: "/home/{{ ops_user }}/scripts/substats_report.sh"
    user: "{{ ops_user }}"
    disabled: yes

- name: Install Dutch Tax Office archive events cron job
  become_user: "{{ ops_user }}"
  cron:
    name: Dutch Tax Office archive events
    minute: 0,15,30,45
    job: "/home/{{ ops_user }}/scm/alert-notification/tools/dbreducer/dutchTaxOffice_del_archives.sh"
    user: "{{ ops_user }}"
    disabled: yes
    
- name: Install Replication Clean cron job
  become_user: "{{ ops_user }}"
  cron:
    name: Clean any replications associated with deleted databases on the source
    minute: "*/10"
    job: "/home/{{ ops_user }}/replication-tools/replicate.js -s https://anbmproddb:<source password>@anbmproddb.cloudant.com -t https://anbmproddbwdc:<target password>@anbmproddbwdc.cloudant.com --sublimit=0 --concurrency 1 --system dummy"
    user: "{{ ops_user }}"
    disabled: yes

- name: Install Replication run cron job
  become_user: "{{ ops_user }}"
  cron:
    name: Run Replication
    minute: 0
    job: "/home/{{ ops_user }}/replication-tools/replicate.js -s https://anbmproddb:<source password>@anbmproddb.cloudant.com -t https://anbmproddbwdc:<target password>@anbmproddbwdc.cloudant.com --sublimit=2500 --concurrency 1"
    user: "{{ ops_user }}"
    disabled: yes

    