---

- name: "Create directories for prometheus main and rules"
  file:
    path: ~/prometheus/rules
    state: directory

- name: "Create data directory for prometheus"
  file:
    path: ~/prometheus/data
    state: directory
    mode: 0777

- name: "Setup prometheus configuration"
  import_tasks: prometheus_config.yml
  vars:
    - fqhnA: "{{ lookup('env', 'replica_a_fqhn') }}"
    - fqhnB: "{{ lookup('env', 'replica_b_fqhn') }}"
    - pushgateway: "{{ lookup('env', 'pushgateway_ip') }}"
    - general_password: "{{ lookup('env', 'general_password') }}"

- name: "Copy test-rules config"
  copy:
    src: test-rules.yml.tar.gz
    dest: ~/prometheus/rules/test-rules.yml.tar.gz

- name: "Decompress test-rule file"
  shell: cd ~/prometheus/rules; tar -zxf test-rules.yml.tar.gz; rm test-rules.yml.tar.gz; cd

- name: "Login Docker before pulling images"
  shell: docker login netcool-sae-docker-local.artifactory.swg-devops.com -u "{{ lookup('env', 'docker_username') }}" -p "{{ lookup('env', 'docker_password') }}"
  become: true

- name: "Pull prometheus image"
  shell: docker pull netcool-sae-docker-local.artifactory.swg-devops.com/netcool-sae/prometheus
  become: true

- name: "Start prometheus container"
  shell: docker run -d -p 127.0.0.1:9090:9090 --name=prometheus -v ~/prometheus/:/etc/prometheus/ netcool-sae-docker-local.artifactory.swg-devops.com/netcool-sae/prometheus --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/etc/prometheus/data --storage.tsdb.retention.time=90d

- name: "Pull thanos image"
  shell: docker pull netcool-sae-docker-local.artifactory.swg-devops.com/netcool-sae/thanos
  become: true
  tags:
    - thanos-sidecar
  
- name: "Start thanos-sidecar container"
  shell: docker run -d --network="host" --name=thanos-sidecar -v ~/prometheus/data/:/var/lib/prometheus netcool-sae-docker-local.artifactory.swg-devops.com/netcool-sae/thanos sidecar --tsdb.path /var/lib/prometheus --prometheus.url http://127.0.0.1:9090 --http-address 0.0.0.0:19191 --grpc-address 0.0.0.0:19090
  tags:
    - thanos-sidecar 
