---

- name: Install hvac (Vault library for Python)
  pip:
    name: hvac
    state: latest
    executable: pip3
    
- name: Install Vault CLI
  raw: wget https://releases.hashicorp.com/vault/0.11.5/vault_0.11.5_linux_amd64.zip; unzip ./vault_0.11.5_linux_amd64.zip; mv ./vault /usr/local/bin; rm -rf ./vault_0.11.5_linux_amd64.zip