#
# Install MotionPro VPN client for SoftLayer connection
#
---

- name: Download MotionPro VPN client
  raw: wget -P /tmp/ -nv "https://speedtest.dal05.softlayer.com/array/MotionPro_Linux_Ubuntu_x86-64_1.1.1.sh"
  
- name: Change installer file permission
  raw: chmod +x /tmp/MotionPro_Linux_Ubuntu_x86-64_1.1.1.sh
  
- name: Install MotionPro VPN client
  raw: /tmp/MotionPro_Linux_Ubuntu_x86-64_1.1.1.sh

- name: Remove MotionPro VPN client installer
  raw: rm -rf /tmp/MotionPro_Linux_Ubuntu_x86-64_1.1.1.sh