---

- name: "Trigger alert metric via pushgateway"
  shell: echo "disk_usage 90" | curl --data-binary @- http://localhost:9091/metrics/job/test-job/region/us-south/environment/dev/node/server-1/component/node-stats.disk-usage

- name: "Wait for 20s for alert to propagate"
  wait_for: timeout=20

- name: "Check if alert propagated to alertmanager"
  shell: curl -u alertmanager:{{ lookup('env','general_password') }} https://{{ lookup('env','replica_a_fqhn') }}:9093/metrics -k | grep alertmanager_alerts | grep firing
  register: verify_alert

- name: "Fail test if alert was not fired"
  fail:
     msg: No alert fired to alertmanager after trigger
  when: '"0" in verify_alert.stdout'

- name: "Trigger resolve metric via pushgateway"
  shell: echo "disk_usage 10" | curl --data-binary @- http://localhost:9091/metrics/job/test-job/region/us-south/environment/dev/node/server-1/component/node-stats.disk-usage

- name: "Wait for 20s for alert to propagate"
  wait_for: timeout=20

- name: "Check if alert propagated to alertmanager"
  shell: curl -u alertmanager:{{ lookup('env','general_password') }} https://{{ lookup('env','replica_a_fqhn') }}:9093/metrics -k | grep alertmanager_alerts | grep resolved
  register: verify_alert

- name: "Fail test if alert was not resolved"
  fail:
     msg: No alert resolved in alertmanager after trigger
  when: '"0" in verify_alert.stdout'
