---

- name: Install Redis Cli
  apt:
    name: redis-tools
    state: latest

- name: Verify Redis-Cli Installed
  command: redis-cli --version
  register: redis_cli_ver

- debug: 
    msg: "{{redis_cli_ver.stdout}}"
