---

- name: Common Tasks
  hosts: "all"
  roles:
    - role: common
  tags:
   - common

- name: Install Monitor Tools
  hosts: "sremonitor"
  become: true
  roles:
    - role: docker
    - role: monitor-config
  tags:
    - monitor

- name: Install Jenkins Tools
  hosts: "srejenkins"
  become: true
  roles:
    - role: jenkins_sshaccess
    - role: blackbox
    - role: nodejs
    - role: ansible
    - role: ibmcloud-utils
    - role: vault
    - role: reporting-lib
    - role: slvpnclient
    - role: docker
  tags:
    - jenkins

- name: Install Datalayer Tools
  hosts: "sredatalayer"
  become: true
  roles:
    - role: jenkins_sshaccess
    - role: gpg
    - role: nodejs
    - role: kubectl
    - role: helm
    - role: ansible
    - role: ibmcloud-utils
    - role: vault
    - role: slvpnclient
    - role: slcli
    - role: sshpass
    - role: iso-images
    - role: docker
  tags:
    - datalayer

- name: Install SRE Tools
  hosts: "sretools"
  become: true
  roles:
    - role: jenkins_sshaccess
    - role: gpg
    - role: ibmcloud-utils
    - role: docker
    - role: ansible
    - role: slvpnclient
    - role: nodejs
    - role: git
    - role: tools-config
    - role: redis-cli
  tags:
    - tools

- name: Install prometheus replicas
  hosts: "sreprometheus"
  become: true
  roles:
    - role: docker
    - role: prometheus
      become_user: "{{ ops_user }}"
    - role: alertmanager
      become_user: "{{ ops_user }}"
      tags:
        - alertmanager-setup
    - role: haproxy
      tags:
        - haproxy-setup
  tags:
    - prometheus-setup

- name: Install thanos query
  hosts: "srethanosquery"
  become: true
  roles:
    - role: docker
    - role: thanosquery
      become_user: "{{ ops_user }}"
    - role: haproxy
      tags:
        - haproxy-setup
  tags:
    - thanosquery-setup

- name: Test prometheus stack with pushgateway
  hosts: "srepushgateway"
  become: true
  roles:
    - role: docker
    - role: pushgateway
      become_user: "{{ ops_user }}"
      tags:
        - pushgateway-setup
    - role: promtest
      become_user: "{{ ops_user }}"
  tags:
    - prometheus-test

- name: Install ASM Core
  hosts: "sreasmcore"
  roles:
    - role: asmcore
  tags:
    - asmcore
    
- name: Install SonarQube
  hosts: "sresonarqube"
  become: true
  gather_facts: True
  roles:
    - role: docker
    - role: sonarqube
  tags:
    - sonarqube

- name: Install MongoDB Primary Node in Replica Set
  hosts: "cicd_mongodb_primary"
  become: true
  gather_facts: True
  roles:
    - role: docker
    - role: mongodb_primary
  tags:
    - mongodb
    
- name: Install MongoDB Secondary Node in Replica Set
  hosts: "cicd_mongodb_secondary"
  order: inventory
  become: true
  gather_facts: True
  roles:
    - role: docker
    - role: mongodb_secondary
  tags:
    - mongodb