#
# Install blackbox tool
#
---

- name: Download blackbox tool
  raw: git clone https://github.com/StackExchange/blackbox.git /tmp/blackbox
  
- name: Install blackbox tool
  raw: cp /tmp/blackbox/bin/* /usr/local/bin/
  
- name: Remove blackbox tool installer
  raw: rm -rf /tmp/blackbox