---

- name: Check if docker-compose already installed
  shell: which docker-compose || echo "false"
  register: docker_compose_found

- shell: echo $(uname -s)-$(uname -m)
  register: distro
  when: docker_compose_found.stdout == "false"

- name: "Install Docker-compose version {{docker_compose_version}}"
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-{{distro.stdout}}"
    dest: /usr/bin/docker-compose
    mode: '744'
  when: docker_compose_found.stdout == "false"
