#
# Add ansibleuser to servers, disable root
#
---
- name: Add ansibleuser to servers, disable root
  hosts: "all"
  remote_user: root
  tasks:
    - name: Create automation group
      group:
        name: automation

    - name: Create ansible user
      user:
        name: ansibleuser
        group: automation

    - name: Lock password for ansible user
      command: passwd -l ansibleuser

    - name: Create .ssh directory for ansible user
      file:
        path: /home/ansibleuser/.ssh
        mode: 0700
        group: automation
        owner: ansibleuser
        state: directory

    - name: Copy authorised keys into .ssh directory for ansible user
      copy:
        dest: /home/ansibleuser/.ssh/authorized_keys
        src: /root/.ssh/authorized_keys
        group: automation
        owner: ansibleuser
        mode: 0600
        remote_src: true

    - name: Ensure ansible user can sudo
      lineinfile:
        dest: /etc/sudoers
        line: "%automation        ALL=(ALL)       NOPASSWD: ALL"

    - name: Ensure ansible user does not need a tty
      lineinfile:
        dest: /etc/sudoers
        line: "Defaults:%automation !requiretty"

    - name: Lock out root
      remote_user: ansibleuser
      become: true
      lineinfile:
        dest: /etc/ssh/sshd_config
        line: "PermitRootLogin no"
        regexp: "^\\s*PermitRootLogin"

    - name: Restart sshd
      remote_user: ansibleuser
      become: true
      command: systemctl restart sshd.service

    - name: Lock password for root
      command: passwd -l root
