---

- import_tasks: createopsuser.yml
  become: yes
  tags: createopsuser

- import_tasks: configsshkeys.yml
  become: yes
  tags: configsshkeys
  
- import_tasks: vncserver_ubu.yml
  become: yes
  tags: vncserver_ubu
  when: ansible_distribution == "Ubuntu"

- import_tasks: vncserver_rhel.yml
  become: yes
  tags: vncserver_rhel
  when: ansible_distribution == "RedHat"

