#
# Setup vncserver
#
---

- name: Update cache centos systems
  yum:
    update_cache=yes
    
- name: Install packages for vnc server
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - tigervnc
    - tigervnc-server

- name: Create .vnc directory
  file:
    path: /root/.vnc/
    state: directory
    
- name: Setup the xstartup file
  copy:
    src: xstartup
    dest: "/root/.vnc/xstartup"
    mode: "755"
    owner: "root"
    group: "root"

