#
# Setup vncserver
#
---

- name: Update cache Ubuntu
  apt: 
    update_cache=yes
  when: ansible_distribution == "Ubuntu"

- name: Install packages for vnc server
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - vnc4server
    - xfce4
    - xfce4-goodies

- name: Create .vnc directory
  file:
    path: /root/.vnc/
    state: directory
    
- name: Setup the xstartup file
  copy:
    src: xstartup
    dest: "/root/.vnc/xstartup"
    mode: "755"
    owner: "root"
    group: "root"

