---

- name: Create monitor environment directory
  become_user: "{{ ops_user }}"
  file:
    path: "/home/{{ ops_user }}/{{ monitor_env_dir }}"
    mode: 0775
    group: '{{ ops_user }}'
    owner: '{{ ops_user }}'
    state: directory