---

# Set ASMHOME
- name: Set ASMHOME
  lineinfile:
    path: ~/.bash_profile
    regexp: '^ASM_HOME'
    line: ASM_HOME=/opt/ibm/netcool/asm

# SET PATH add ASMHOME/bin to PATH
- name: Set ASMHOME/bin
  lineinfile:
    path: ~/.bash_profile
    regexp: '^PATH'
    line: PATH=/opt/ibm/netcool/asm/bin:$PATH

- name: Start ASM Core
  command: /opt/ibm/netcool/asm/bin/docker-compose up -d
  args:
    chdir: /opt/ibm/netcool/asm
  register: compose_up

- debug: msg="{{compose_up.stderr}}"

# Pause for 60 seconds to allow processes to start and remain running to verify they stay up.
- pause:
    seconds: 60

- name: Check processes are up
  command: chdir=/opt/ibm/netcool/asm /opt/ibm/netcool/asm/bin/docker-compose ps
  args:
    chdir: /opt/ibm/netcool/asm
  register: compose_ps

- debug: msg="{{compose_ps.stdout}}"

