---

- name: "Login Docker before pulling images"
  shell: docker login netcool-sae-docker-local.artifactory.swg-devops.com -u "{{ lookup('env', 'docker_username') }}" -p "{{ lookup('env', 'docker_password') }}"
  become: true

- name: "Pull thanos image"
  shell: docker pull netcool-sae-docker-local.artifactory.swg-devops.com/netcool-sae/thanos
  become: true

- name: "Start thanos-query container"
  shell: docker run -d -p 127.0.0.1:19192:19192 --name=thanos-query netcool-sae-docker-local.artifactory.swg-devops.com/netcool-sae/thanos query --http-address 0.0.0.0:19192 --store {{ lookup('env', 'replica_a_ip') }}:19090 --store {{ lookup('env', 'replica_b_ip') }}:19090 --query.replica-label replica
