---

- name: "Create directories for alertmanager"
  file:
    path: ~/alertmanager
    state: directory

- name: "Copy alertmanager config"
  copy:
    src: alertmanager.yml.tar.gz
    dest: ~/alertmanager/alertmanager.yml.tar.gz

- name: "Decompress configuration file"
  shell: cd ~/alertmanager; tar -zxf alertmanager.yml.tar.gz; rm alertmanager.yml.tar.gz; cd

- name: "Login Docker before pulling images"
  shell: docker login netcool-sae-docker-local.artifactory.swg-devops.com -u "{{ lookup('env', 'docker_username') }}" -p "{{ lookup('env', 'docker_password') }}"
  become: true

- name: "Pull alertmanager image"
  shell: docker pull netcool-sae-docker-local.artifactory.swg-devops.com/netcool-sae/alertmanager
  become: true

- name: "Start alertmanager container for replica a"
  shell: docker run -d -p 127.0.0.1:9093:9093 -p 9094:9094 -p 9094:9094/udp --name=alertmanager -v /home/opsadmin/alertmanager/:/etc/alertmanager netcool-sae-docker-local.artifactory.swg-devops.com/netcool-sae/alertmanager --cluster.peer={{ lookup('env', 'replica_b_ip') }}:9094 --cluster.advertise-address {{ lookup('env', 'replica_a_ip') }}:9094 --config.file=/etc/alertmanager/alertmanager.yml --log.level=debug
  when: ansible_default_ipv4.address == lookup('env', 'replica_a_ip')

- name: "Start alertmanager container for replica b"
  shell: docker run -d -p 127.0.0.1:9093:9093 -p 9094:9094 -p 9094:9094/udp --name=alertmanager -v /home/opsadmin/alertmanager/:/etc/alertmanager netcool-sae-docker-local.artifactory.swg-devops.com/netcool-sae/alertmanager --cluster.peer={{ lookup('env', 'replica_a_ip') }}:9094 --cluster.advertise-address {{ lookup('env', 'replica_b_ip') }}:9094 --config.file=/etc/alertmanager/alertmanager.yml --log.level=debug
  when: ansible_default_ipv4.address == lookup('env', 'replica_b_ip')
